# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bpcaNet <- function(myMat, N, D, hidden, numberOfNonNAvaluesInEachCol, nomissIndex, missIndex, nMissing, nPcs = 2L, threshold = 1e-4, maxIterations = 200L) {
    .Call('ppcaNet_bpcaNet', PACKAGE = 'ppcaNet', myMat, N, D, hidden, numberOfNonNAvaluesInEachCol, nomissIndex, missIndex, nMissing, nPcs, threshold, maxIterations)
}

ppcaNet <- function(myMat, N, D, C, hidden, nMissing, nPcs = 2L, threshold = 1e-5, maxIterations = 1000L) {
    .Call('ppcaNet_ppcaNet', PACKAGE = 'ppcaNet', myMat, N, D, C, hidden, nMissing, nPcs, threshold, maxIterations)
}

